name: PR
on:
  pull_request:

permissions:
  checks: write
  contents: read

jobs:
  test:
    name: 'Terragrunt'
    runs-on: ubuntu-latest
    env:
      TF_VERSION: '1.13.5'
      TG_VERSION: '0.93.8'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Terragrunt
        uses: autero1/action-terragrunt@v3.0.2
        with:
          terragrunt-version: ${{ env.TG_VERSION }}
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false
          terraform_version: ${{ env.TF_VERSION }}
      - name: Plan all
        run: |
          cd example_project
          terragrunt run --all plan --non-interactive
      - uses: actions/setup-node@v4
        with:
          node-version: '24'
          cache: 'npm'
      - run: npm ci
      - run: npm test
      - run: npm run lint
      - run: npm run build
      - name: Report plans
        uses: ./
        with:
          pretty_name_regex: '/example_project/?(\w+)?/(\w+).diff'
          pretty_name_separator: '/'
